site_name: M2QF | Cutting-Edge project | Subject 2

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lcsrodriguez/CuttingEdge-Milliman

repo_url: https://github.com/lcsrodriguez/CuttingEdge-Milliman
repo_name: GitHub repo
site_description: Official documentation of Cutting-Edge project
site_author: Amal BACHA - Dalia BARBI - Khalil BATTIKH - Lucas RODRIGUEZ - Naïm SOUNI
copyright: Copyright &copy; 2023 Amal BACHA - Dalia BARBI - Khalil BATTIKH - Lucas RODRIGUEZ - Naïm SOUNI<br>Academic work &bull; <i>January 2023 - Present</i>
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - mkdocstrings
  - section-index

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/custom.css

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - How To: how-to.md
  - Architecture: architecture.md
  - Code Reference: reference/summary.md
  - Bibliography: bibliography.md
  - Documents: documents.md
  - History: git.md
#   - References:
# - Summary: reference/summary.md
# - BlackScholes: reference/BlackScholes.md
# - CIR: reference/CIR.md
# - Constants: reference/Constants.md
# - EM: reference/EquityModel.md
# - hw: reference/HullWhite.md
# - M: reference/Model.md
# - RM: reference/RatesModel.md
# - U: reference/Utils.md
# - v: reference/Vasicek.md
