site_name: Cutting-Edge project
theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Reference: reference.md
